#!/usr/bin/env bash


# arg1 = promp1
# arg2 = cmd

if [ "$ROFI_RETV" == "0" ]
then
	# prompt = $1
	echo -e "\0prompt\x1f$1"
	echo -e "yes"
	echo -e "\0date\x1ftrue"
	echo -e "no"
	exit 0
fi


if [ "$3" == "yes" ] 
then 
	# idk what this is look in rofi doc
	coproc ( $2 > /dev/null  2>&1 )
fi




